services:
  frontend:
    container_name: "frontend" # Name of the container
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=api_url
      - VITE_API_USERNAME=api_username
      - VITE_API_PASSWORD=api_password
