version: "3.8"
services:
  react:
    container_name: "News Hyperlocalizer" # Name of the container
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_AUTH_TOKEN=195479750494cd5124e8481a607347b4b8abb48c
