name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Convert OWNER to lowercase
        run: echo "OWNER=$(echo $OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.OWNER }}/news-hyperlocalizer:latest

      - name: Make image public
        run: |
          IMAGE_ID=$(echo ${{ steps.build-and-push.outputs.digest }} | cut -d ':' -f 2)
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/packages/container/news-hyperlocalizer/versions/$IMAGE_ID \
            -d '{"visibility":"public"}'
